version: "3.7"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - $PWD/conf/prometheus:/etc/prometheus
      - $PWD/data/prometheus:/prometheus-data

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
       - $PWD/data/grafana:/var/lib/grafana
      #  - $PWD/data/grafana/provisioning:/etc/grafana/provisioning
      #  - $PWD/conf/grafana:/etc/grafana
      #  - $PWD/logs/grafana:/var/log/grafana

