{
 "title": "DataServer 1.5",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "kubernetes-pods" },
   {
    "name": "project",
    "label": "project",
    "query": "label_values(dataserver_myproxy_connections_max_open,project)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},stage)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\"},service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\",service=\"$service\"},kubernetes_pod_name)"
   },
   {
    "name": "query",
    "label": "command",
    "query": "label_values(db_exec_timing_count{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\",service=\"$service\"}, command)"
   },
   { "name": "quantile", "label": "quantile", "query": "0.5,  0.95, 0.99, 1" }
  ]
 },
 "panels": [
  {
   "title": "总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataserver Instances",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count (dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\",service=\"$service\",server_id=\"0\"})"
      }
     ]
    },
    {
     "title": "Mysql Instances",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(count by(server_id) (dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\",service=\"$service\",server_id!=\"0\"}))"
      }
     ]
    },
    {
     "title": "SIID Domains",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "count (siid_next{job=\"$job\", project=\"$project\", env_name=\"$env\",stage=\"$stage\",service=\"$service\"})"
      }
     ]
    },
    {
     "title": "API QPS",
     "type": "stat",
     "description": "所选区间内的最大值",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(myproxy_option_access_count{job=\"$job\", project=\"$project\", env_name=\"$env\",stage=\"$stage\",service=\"$service\"}[5m]))",
       "legendFormat": "API QPS"
      }
     ]
    },
    {
     "title": "队列总长度",
     "type": "stat",
     "description": "所选区间内的最大值",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(max by (queue) (asynq_status_topic_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}))",
       "legendFormat": "队列总长度"
      }
     ]
    },
    {
     "title": "延迟队列总长度",
     "type": "stat",
     "description": "所选区间内的最大值",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(max by (queue) (delayq_status_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}))"
      }
     ]
    },
    {
     "title": "Slowest API",
     "type": "stat",
     "description": "所选时间区间内的最大值",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(myproxy_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\",stage=\"$stage\",service=\"$service\"})"
      }
     ]
    },
    {
     "title": "DB Errors",
     "type": "stat",
     "description": "所选时间区间内的最大值",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(db_exec_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"})"
      }
     ]
    },
    {
     "title": "Asynq队列长度",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (queue) (asynq_status_topic_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "延迟队列长度",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (queue) (delayq_status_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency && QPS  (POD:$pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "session status qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(session_status{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"} [2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{status}}"
      }
     ]
    },
    {
     "title": "session count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "session_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "SQL Rewritten counter",
     "type": "graph",
     "description": "执行一条sql语句，在myproxy会分成多少条sql语句",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "db_rewritten_counter{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}-{{command}}"
      }
     ]
    },
    {
     "title": "API Latency",
     "type": "graph",
     "description": "**Api Cost Time **\n\nAPI访问操作消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "myproxy_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "API QPS",
     "type": "graph",
     "description": "**Api QPS**\n\nAPI访问QPS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (option)(rate(myproxy_option_access_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}[2m]))",
       "legendFormat": "{{option}}"
      }
     ]
    },
    {
     "title": "Cache Latency",
     "type": "graph",
     "description": "**Cache Cost Time **\n\n缓存(redis)时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "myproxy_option_cache{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Cache QPS",
     "type": "graph",
     "description": "**Cache QPS**\n\n缓存(redis)QPS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (option)(rate(myproxy_option_cache_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}[2m]))",
       "legendFormat": "{{option}}"
      }
     ]
    },
    {
     "title": "Store Latency",
     "type": "graph",
     "description": "**Cost Time of Database**\n\n数据库访问消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{kubernetes_pod_name}}: table: {{table_name}}  quantile:{{quantile}}"
      }
     ]
    },
    {
     "title": "Store QPS",
     "type": "graph",
     "description": "**Database QPS**\n\n数据库访问QPS 包含异步",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(db_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}[2m])) by (command)",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "逻辑处理Latency",
     "type": "graph",
     "description": "**逻辑处理**\n\n包含接口逻辑和异步落地等所有逻辑的耗时",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "myproxy_option_service{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{kubernetes_pod_name}}: option:{{option}}  quantile:{{quantile}} "
      }
     ]
    },
    {
     "title": "逻辑处理QPS",
     "type": "graph",
     "description": "**逻辑处理 QPS**\n\n包含接口逻辑和异步落地等所有逻辑的QPS",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(myproxy_option_service_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}[2m])) by (option)",
       "legendFormat": "{{option}}"
      }
     ]
    },
    {
     "title": "Node Latency",
     "type": "graph",
     "description": "**Node Cost Time **\n\nNode访问操作消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "myproxy_option_node{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{kubernetes_pod_name}}_id:{{id}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Node QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (id,option)(rate(myproxy_option_node_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m]))",
       "legendFormat": "id:{{id}}-{{option}}"
      }
     ]
    },
    {
     "title": "Conn Latency",
     "type": "graph",
     "description": "**Conn Cost Time **\n\nConn访问操作消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "myproxy_option_conn{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_id:{{id}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Conn QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (id,option)(rate(myproxy_option_conn_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m]))",
       "legendFormat": "id:{{id}}-{{option}}"
      }
     ]
    },
    {
     "title": "Slow of Api",
     "type": "graph",
     "description": "**Slow of Api**\n\nAPI慢操作",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "slow_myproxy_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Slow of Store",
     "type": "graph",
     "description": "**Slow Option of Database**\n\n数据库慢操作",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "slow_myproxy_option_store{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "SIID Next QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name,domain) (rate(siid_next{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[5m]))",
       "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
      }
     ]
    },
    {
     "title": "SIID Quantum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "siid_quantum{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}",
       "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
      }
     ]
    },
    {
     "title": "SIID Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "siid_max{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}",
       "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
      }
     ]
    },
    {
     "title": "SIID Left",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "siid_n_left{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}",
       "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
      }
     ]
    }
   ]
  },
  {
   "title": "队列",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asynq发布任务速率",
     "type": "graph",
     "description": "每秒产生异步任务的速度",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(asynq_produce_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Topic}}"
      }
     ]
    },
    {
     "title": "Delayq发布任务速率",
     "type": "graph",
     "description": "每秒产生异步任务的速度",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(delayq_produce_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Topic}}"
      }
     ]
    },
    {
     "title": "Asynq处理任务速率",
     "type": "graph",
     "description": "每秒处理异步任务的速度",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(asynq_handle_task{job=\"$job\", project=\"$project\", kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Topic}}"
      }
     ]
    },
    {
     "title": "Delayq处理任务速率",
     "type": "graph",
     "description": "每秒处理异步任务的速度",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(delayq_handle_task{job=\"$job\", project=\"$project\", kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Topic}}"
      }
     ]
    },
    {
     "title": "Asynq队列长度",
     "type": "graph",
     "description": "当前异步队列长度",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (queue) (asynq_status_topic_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Delayq队列长度",
     "type": "graph",
     "description": "当前异步队列长度",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (queue) (delayq_status_topic_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Asynq处理任务失败数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟处理异步任务错误累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_handle_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Delayq处理任务失败数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟处理异步任务错误累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_handle_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Asynq任务因为长时间未被处理而重采集数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟因为长时间未被处理而重采集累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_reclaim_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Delayq任务因为长时间未被处理而重采集数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟因为长时间未被处理而重采集累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_reclaim_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Asynq发布异步任务失败数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟发布异步任务产生错误累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_produce_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Delayq发布异步任务失败数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟发布异步任务产生错误累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_produce_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Asynq产生死信任务数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟产生死信任务累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_dead_letter_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{Topic}}"
      }
     ]
    },
    {
     "title": "Delayq产生死信任务数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟产生死信任务累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_dead_letter_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{Topic}}"
      }
     ]
    }
   ]
  },
  { "title": "Redis (POD:$pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "cache hits / 2min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(redis_cache_hits{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "cache miss / 2min",
   "type": "graph",
   "description": "number of times free connection was found in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(redis_cache_miss{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "pool hits / 2分钟",
   "type": "graph",
   "description": "number of times free connection was found in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(go_redis_pool_stats_connections_hits{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "pool misses / 2分钟",
   "type": "graph",
   "description": "number of times free connection was NOT found in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(go_redis_pool_stats_connections_misses{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "timeouts",
   "type": "graph",
   "description": "number of times a wait timeout occurred",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_timeouts{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "total_conns",
   "type": "graph",
   "description": "number of total connections in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_total_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "idle_conns",
   "type": "graph",
   "description": "number of idle connections in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_idle_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "stale_conns",
   "type": "graph",
   "description": "number of stale connections removed from the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_stale_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Exec QPS",
   "type": "graph",
   "description": "执行redis命令qps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (s_command) (rate(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m]))",
     "legendFormat": "{{s_command}}"
    }
   ]
  },
  {
   "title": "Exec Error / 5分钟",
   "type": "graph",
   "description": "每5分钟redis执行命令错误数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (s_command) (increase(redis_exec_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[5m]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Pipeline命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Pipeline\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "String命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"Strings|String\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Lists命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"Lists｜List\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Hash命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"Hashes｜Hash\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "SortedSet命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"SortedSets|SortedSet\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Set命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"Sets|Set\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Scripting命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Scripting\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Bitmap命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Bitmap\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Stream命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"Streams|Stream\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Geospatial命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=~\"Geo|Geospatial\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Server命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Server\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Cluster命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Cluster\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Generic命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Generic\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Connection命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Connection\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "HyperLog命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"HyperLog\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "PubSub命令集执行耗时(分位值：$quantile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"PubSub\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "DB (POD:$pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "pool max connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dataserver_myproxy_connections_max_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}: Max Open"
      }
     ]
    },
    {
     "title": "pool open connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dataserver_myproxy_connections_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}: Open"
      }
     ]
    },
    {
     "title": "pool close connections / 5 minutes",
     "type": "graph",
     "description": "max idle: The total number of connections closed due to SetMaxIdleConns\n\nmax life time: The total number of connections closed due to SetConnMaxLifetime\n\nmax idle time: The total number of connections closed due to SetConnMaxIdleTime",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(dataserver_myproxy_connections_closed_max_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}: max idle"
      },
      {
       "expr": "increase(dataserver_myproxy_connections_closed_max_lifetime{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}: max life time"
      },
      {
       "expr": "increase(dataserver_myproxy_connections_closed_max_idle_time{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}: max idle time"
      }
     ]
    },
    {
     "title": "pool use and idle connections",
     "type": "graph",
     "description": "in use: The number of connections currently in use\n\nidle: The number of idle connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dataserver_myproxy_connections_in_use{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}: in use"
      },
      {
       "expr": "dataserver_myproxy_connections_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}:  idle"
      }
     ]
    },
    {
     "title": "block commands wait for connections / 5 minutes",
     "type": "graph",
     "description": "the total number of waits / 5min",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(dataserver_myproxy_connections_waited_for{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}  - {{db_name}}waited for"
      }
     ]
    },
    {
     "title": "block get connections / second",
     "type": "graph",
     "description": "连接池获取链接阻塞占用时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(dataserver_myproxy_connections_blocked_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} - {{db_name}}"
      }
     ]
    },
    {
     "title": "TOP 10 slowest command ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(command) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=~\"$service\"}))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "TOP 10 Table slowest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(table_name) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=~\"$service\"}))",
       "legendFormat": "{{table_name}}"
      }
     ]
    },
    {
     "title": "DB Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (command, quantile) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=~\"$service\",quantile=~\"$quantile\"})",
       "legendFormat": "{{command}}:  quantile:{{quantile}}"
      }
     ]
    },
    {
     "title": "DB Error / 1 minute",
     "type": "graph",
     "description": "每分钟DB错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (command)(increase(db_exec_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}[2m]))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "DB QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (command, table_name) (rate(db_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",service=\"$service\"}[2m]))",
       "legendFormat": "{{table_name}}-{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "go process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU使用",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,kubernetes_pod_name)(rate(goruntime_process_cpu_seconds_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "graph",
     "description": "**Total Used Memory**\n\n已使用内存信息\n\n* *go_memstats_sys_bytes*:服务现在系统使用的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Off-Heap",
     "type": "graph",
     "description": "**Memory in Off-Heap**\n\n堆外内存信息\n\n* *go_memstats_mspan_inuse_bytes*:用于测试用的结构体使用的字节数.\n* *go_memstats_mspan_sys_bytes*:系统为测试用的结构体分配的字节数.\n* *go_memstats_mcache_inuse_bytes*:mcache结构体申请的字节数(不会被视为垃圾回收).\n* *go_memstats_mcache_sys_bytes*:操作系统申请的堆空间用于mcache的字节数.\n* *go_memstats_buck_hash_sys_bytes*:用于剖析桶散列表的堆空间字节.\n* *go_memstats_gc_sys_bytes*:圾回收标记元信息使用的内存字节.\n* *go_memstats_next_gc_bytes*:垃圾回收器检视的内存大小.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mspan_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mspan_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mcache_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mcache_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_buck_hash_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_gc_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_next_gc_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "graph",
     "description": "**Memory in Heap**\n\n堆内存信息\n* *go_memstats_heap_alloc_bytes*:服务分配的堆内存字节数.\n* *go_memstats_heap_sys_bytes*:系统分配的作为运行栈的内存.\n* *go_memstats_heap_idle_bytes*:申请但是未分配的堆内存或者回收了的堆内存（空闲）字节数.\n* *go_memstats_heap_inuse_bytes*:正在使用的堆内存字节数.\n* *go_memstats_heap_released_bytes*:返回给OS的堆内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_alloc_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_idle_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_released_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "description": "**Memory in Stack**\n\n栈内存信息\n\n* *go_memstats_stack_inuse_bytes*: 正在使用的栈字节数.\n* *go_memstats_stack_sys_bytes*: 系统分配的作为运行栈的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_stack_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_stack_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "graph",
     "description": "**Rate of Objects Allocated**\n\n每秒产生的堆对象数量\n\n``rate(go_memstats_mallocs_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "description": "**Number of Live Objects**\n\n* *go_memstats_mallocs_total*:服务malloc的次数.\n* *go_memstats_frees_total*:内存释放统计.\n\n``go_memstats_mallocs_total - go_memstats_frees_total``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}-go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rates of Heap Object",
     "type": "graph",
     "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_heap_objects{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "graph",
     "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "graph",
     "description": "**Rate of a Pointer Dereferences**\n\n* * go_memstats_lookups_total:被runtime监视的指针数.\n\n``rate(go_memstats_lookups_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "**Goroutines**\n\n\n协程数量\n\n* *go_goroutines*:当前存在的协程数量.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_goroutines_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "description": "**GC duration quantile**\n\n* *go_gc_duration_seconds*:垃圾收集周期的暂停持续时间.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_gc_duration_seconds_{{kubernetes_pod_name}}_{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}