{
 "title": "Dataserver 1.4",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "kubernetes-pods" },
   {
    "name": "project",
    "label": "project",
    "query": "label_values(dataserver_connections_max_open,project)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(dataserver_connections_max_open{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(dataserver_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},stage)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(dataserver_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},kubernetes_pod_name)"
   },
   {
    "name": "query",
    "label": "query",
    "query": "label_values(db_exec_timing{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\",kubernetes_pod_name=\"$pod\"},query)"
   },
   { "name": "quantile", "label": "quantile", "query": "0.5, 0.75, 0.95, 1" }
  ]
 },
 "panels": [
  {
   "title": "Asynq队列长度",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (queue) (asynq_status_topic_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "延迟队列长度",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (queue) (delayq_status_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "go 基础指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "graph",
     "description": "**Memory in Off-Heap**\n\n堆外内存信息\n\n* *go_memstats_mspan_inuse_bytes*:用于测试用的结构体使用的字节数.\n* *go_memstats_mspan_sys_bytes*:系统为测试用的结构体分配的字节数.\n* *go_memstats_mcache_inuse_bytes*:mcache结构体申请的字节数(不会被视为垃圾回收).\n* *go_memstats_mcache_sys_bytes*:操作系统申请的堆空间用于mcache的字节数.\n* *go_memstats_buck_hash_sys_bytes*:用于剖析桶散列表的堆空间字节.\n* *go_memstats_gc_sys_bytes*:圾回收标记元信息使用的内存字节.\n* *go_memstats_next_gc_bytes*:垃圾回收器检视的内存大小.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mspan_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mspan_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mcache_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mcache_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_buck_hash_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_gc_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_next_gc_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "graph",
     "description": "**Memory in Heap**\n\n堆内存信息\n* *go_memstats_heap_alloc_bytes*:服务分配的堆内存字节数.\n* *go_memstats_heap_sys_bytes*:系统分配的作为运行栈的内存.\n* *go_memstats_heap_idle_bytes*:申请但是未分配的堆内存或者回收了的堆内存（空闲）字节数.\n* *go_memstats_heap_inuse_bytes*:正在使用的堆内存字节数.\n* *go_memstats_heap_released_bytes*:返回给OS的堆内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_alloc_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_idle_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_released_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "description": "**Memory in Stack**\n\n栈内存信息\n\n* *go_memstats_stack_inuse_bytes*: 正在使用的栈字节数.\n* *go_memstats_stack_sys_bytes*: 系统分配的作为运行栈的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_stack_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_stack_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "graph",
     "description": "**Total Used Memory**\n\n已使用内存信息\n\n* *go_memstats_sys_bytes*:服务现在系统使用的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "description": "**Number of Live Objects**\n\n* *go_memstats_mallocs_total*:服务malloc的次数.\n* *go_memstats_frees_total*:内存释放统计.\n\n``go_memstats_mallocs_total - go_memstats_frees_total``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}-go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "graph",
     "description": "**Rate of Objects Allocated**\n\n每秒产生的堆对象数量\n\n``rate(go_memstats_mallocs_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "graph",
     "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "graph",
     "description": "**Rate of a Pointer Dereferences**\n\n* * go_memstats_lookups_total:被runtime监视的指针数.\n\n``rate(go_memstats_lookups_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "**Goroutines**\n\n\n协程数量\n\n* *go_goroutines*:当前存在的协程数量.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_goroutines_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "description": "**GC duration quantile**\n\n* *go_gc_duration_seconds*:垃圾收集周期的暂停持续时间.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_gc_duration_seconds_{{kubernetes_pod_name}}_{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "dataserver 指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Asynq发布任务速率",
     "type": "graph",
     "description": "每秒产生异步任务的速度\n\n发布任务的速率和处理任务的速率的总数相近最好\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(asynq_produce_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Topic}}"
      }
     ]
    },
    {
     "title": "Asynq处理任务速率",
     "type": "graph",
     "description": "每秒处理异步任务的速度\n\n发布任务的速率和处理任务的速率的总数相近最好",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(asynq_handle_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Topic}}"
      }
     ]
    },
    {
     "title": "Asynq发布异步任务失败数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟发布异步任务产生错误累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_produce_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "Asynq队列长度",
     "type": "graph",
     "description": "当前异步队列长度\n\n当前未处理的任务数，指标值越高表示处理能力越差，任务有堆积",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (queue) (asynq_status_topic_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "Asynq产生死信任务数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟产生死信任务累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_dead_letter_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{Topic}}"
      }
     ]
    },
    {
     "title": "Asynq处理任务失败数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟处理异步任务错误累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_handle_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
      }
     ]
    },
    {
     "title": "延迟队列发布任务速率",
     "type": "graph",
     "description": "延迟队列 每秒产生任务的速度\n\n发布任务的速率和处理任务的速率的总数相近最好\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(delayq_produce{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Queue}}"
      }
     ]
    },
    {
     "title": "Asynq任务因为长时间未被处理而重采集数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟因为长时间未被处理而重采集累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(asynq_reclaim_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}{{Topic}}"
      }
     ]
    },
    {
     "title": "延迟队列处理任务速率",
     "type": "graph",
     "description": "延迟队列 每秒处理任务的速度\n\n发布任务的速率和处理任务的速率的总数相近最好",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(delayq_handle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}} - {{Queue}}"
      }
     ]
    },
    {
     "title": "延迟队列长度",
     "type": "graph",
     "description": "当前延迟队列长度\n\n当前未处理的任务数，指标值越高表示处理能力越差，任务有堆积",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (queue) (delayq_status_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"})",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "延迟队列发布任务错误数量 / 10分钟",
     "type": "graph",
     "description": "延迟队列 每10分钟发布任务错误数量累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_produce_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{Queue}}"
      }
     ]
    },
    {
     "title": "延迟队列处理任务错误数量 / 10分钟",
     "type": "graph",
     "description": "延迟队列 每10分钟处理任务错误数量累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_handle_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{Queue}}"
      }
     ]
    },
    {
     "title": "延迟队列因为长时间未被处理而重采集数量 / 10分钟",
     "type": "graph",
     "description": "每10分钟因为长时间未被处理而重采集累计数",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_reclaim{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{Queue}}"
      }
     ]
    },
    {
     "title": "延迟队列采集错误数量 / 10分钟",
     "type": "graph",
     "description": "延迟队列 每10分钟采集错误数量累计数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(delayq_poll_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{Queue}}"
      }
     ]
    },
    {
     "title": "延迟队列重采集错误",
     "type": "graph",
     "description": "延迟队列重采集错误累计值",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delayq_reclaim_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: {{Queue}}"
      }
     ]
    },
    {
     "title": "Cost Time of Service",
     "type": "graph",
     "description": "**Cost Time of Service**\n\n服务逻辑消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dataserver_option_service{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Cost Time of Api",
     "type": "graph",
     "description": "**Api Cost Time**\n\nAPI访问操作消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dataserver_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Cost Time of Cache",
     "type": "graph",
     "description": "**Cost Time of Cache**\n\n缓存消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dataserver_option_cache{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Cost Time of Database",
     "type": "graph",
     "description": "**Cost Time of Database**\n\n数据库访问消耗时间",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Slow Option of Service",
     "type": "graph",
     "description": "**Slow Option of Service**\n\n服务慢操作",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "slow_dataserver_option_service{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Slow Option of Api",
     "type": "graph",
     "description": "**Slow of Api**\n\nAPI慢操作",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "slow_dataserver_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Slow Option of Cache",
     "type": "graph",
     "description": "**Slow Option of Cache**\n\n缓存慢操作",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "slow_dataserver_option_cache{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    },
    {
     "title": "Slow Option of Database",
     "type": "graph",
     "description": "**Slow Option of Database**\n\n数据库慢操作",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "slow_dataserver_option_database{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "hits / 2分钟",
     "type": "graph",
     "description": "number of times free connection was found in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(go_redis_pool_stats_connections_hits{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "misses / 2分钟",
     "type": "graph",
     "description": "number of times free connection was NOT found in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(go_redis_pool_stats_connections_misses{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "timeouts",
     "type": "graph",
     "description": "number of times a wait timeout occurred",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_timeouts{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "total_conns",
     "type": "graph",
     "description": "number of total connections in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_total_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "idle_conns",
     "type": "graph",
     "description": "number of idle connections in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_idle_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "stale_conns",
     "type": "graph",
     "description": "number of stale connections removed from the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_stale_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Net Latency",
     "type": "graph",
     "description": "统计redis网络耗时情况",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "redis_net_latency", "legendFormat": "{{Name}}-{{quantile}}" }
     ]
    },
    {
     "title": "Sleep Timing",
     "type": "graph",
     "description": "redis命令执行错误会sleep",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_sleep_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{command}}-attempt: {{attempt}} error:{{error}} quantile:{{quantile}}"
      }
     ]
    },
    {
     "title": "Exec QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (s_command) (rate(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m]))",
       "legendFormat": "{{s_command}}"
      }
     ]
    },
    {
     "title": "每分钟Sleep次数",
     "type": "graph",
     "description": "redis命令执行错误会sleep",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_sleep_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])*60",
       "legendFormat": "{{command}}-attempt: {{attempt}} error:{{error}}"
      }
     ]
    },
    {
     "title": "Pipeline命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Pipeline\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Exec Error / 5分钟",
     "type": "graph",
     "description": "每5分钟redis执行命令错误数量",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (s_command) (increase(redis_exec_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[5m]))",
       "legendFormat": "{{s_command}}"
      }
     ]
    },
    {
     "title": "Lists命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Lists\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Strings命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Strings\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "SortedSets命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"SortedSets\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Keys命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Keys\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Scripting命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Scripting\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Hashes命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Hashes\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Streams命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Streams\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Sets命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Sets\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Server命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Server\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Geo命令集执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Geo\",quantile=~\"$quantile\"}",
       "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "连接池最大连接数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dataserver_connections_max_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: Max Open"
      }
     ]
    },
    {
     "title": "连接池当前连接数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dataserver_connections_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: Open"
      }
     ]
    },
    {
     "title": "关闭连接 / 5分钟",
     "type": "graph",
     "description": "max idle: The total number of connections closed due to SetMaxIdleConns\n\nmax life time: The total number of connections closed due to SetConnMaxLifetime\n\nmax idle time: The total number of connections closed due to SetConnMaxIdleTime",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(dataserver_connections_closed_max_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: max idle"
      },
      {
       "expr": "increase(dataserver_connections_closed_max_lifetime{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: max life time"
      },
      {
       "expr": "increase(dataserver_connections_closed_max_idle_time{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: max idle time"
      }
     ]
    },
    {
     "title": "使用和空闲连接数",
     "type": "graph",
     "description": "in use: The number of connections currently in use\n\nidle: The number of idle connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dataserver_connections_in_use{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: in use"
      },
      {
       "expr": "dataserver_connections_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}:  idle"
      }
     ]
    },
    {
     "title": "等待链接的待执行命令数 / 5分钟",
     "type": "graph",
     "description": "the total number of waits / 5min",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(dataserver_connections_waited_for{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}} waited for"
      }
     ]
    },
    {
     "title": "获取链接阻塞时间 /秒",
     "type": "graph",
     "description": "连接池获取链接阻塞占用时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(dataserver_connections_blocked_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "TOP 10 慢查询",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(command,table_name) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}))",
       "legendFormat": "{{table_name}} {{command}}"
      }
     ]
    },
    {
     "title": "错误次数/秒",
     "type": "graph",
     "description": "每秒DB错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_error{status!=\"ok\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{table_name}}-{{command}}"
      }
     ]
    },
    {
     "title": "direct 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"direct\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "direct QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"direct\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "stmt_prepare 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"stmt_prepare\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "stmt_prepare QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"stmt_prepare\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "stmt_execute 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"stmt_execute\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "stmt_execute QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"stmt_execute\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "query 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"query\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "query QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"query\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "count 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"count\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "count QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"count\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "upsert 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"upsert\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "upsert QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"upsert\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "delete 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"delete\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "delete QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"delete\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "get 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"get\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "get QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"get\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    },
    {
     "title": "select 执行耗时(分位值：$quantile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{command=\"select\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{{kubernetes_pod_name}}: {{table_name}}: {{quantile}}"
      }
     ]
    },
    {
     "title": "select QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_timing_count{command=\"select\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: {{table_name}}"
      }
     ]
    }
   ]
  }
 ]
}