{
 "title": "Dataserver",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "kubernetes-pods" },
   {
    "name": "project",
    "label": "project",
    "query": "label_values(dataserver_connections_max_open,project)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(dataserver_connections_max_open{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(dataserver_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},stage)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(dataserver_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},kubernetes_pod_name)"
   },
   {
    "name": "query",
    "label": "query",
    "query": "label_values(db_exec_timing{job=\"$job\", project=\"$project\",env_name=\"$env\",stage=\"$stage\",kubernetes_pod_name=\"$pod\"},query)"
   },
   { "name": "quantile", "label": "quantile", "query": "0.5, 0.75, 0.95, 1" }
  ]
 },
 "panels": [
  { "title": "go 基础指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "description": "**Memory in Off-Heap**\n\n堆外内存信息\n\n* *go_memstats_mspan_inuse_bytes*:用于测试用的结构体使用的字节数.\n* *go_memstats_mspan_sys_bytes*:系统为测试用的结构体分配的字节数.\n* *go_memstats_mcache_inuse_bytes*:mcache结构体申请的字节数(不会被视为垃圾回收).\n* *go_memstats_mcache_sys_bytes*:操作系统申请的堆空间用于mcache的字节数.\n* *go_memstats_buck_hash_sys_bytes*:用于剖析桶散列表的堆空间字节.\n* *go_memstats_gc_sys_bytes*:圾回收标记元信息使用的内存字节.\n* *go_memstats_next_gc_bytes*:垃圾回收器检视的内存大小.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_gc_sys_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_next_gc_bytes_{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "description": "**Memory in Heap**\n\n堆内存信息\n* *go_memstats_heap_alloc_bytes*:服务分配的堆内存字节数.\n* *go_memstats_heap_sys_bytes*:系统分配的作为运行栈的内存.\n* *go_memstats_heap_idle_bytes*:申请但是未分配的堆内存或者回收了的堆内存（空闲）字节数.\n* *go_memstats_heap_inuse_bytes*:正在使用的堆内存字节数.\n* *go_memstats_heap_released_bytes*:返回给OS的堆内存.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_sys_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_idle_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_heap_released_bytes_{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "description": "**Memory in Stack**\n\n栈内存信息\n\n* *go_memstats_stack_inuse_bytes*: 正在使用的栈字节数.\n* *go_memstats_stack_sys_bytes*: 系统分配的作为运行栈的内存.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes_{{kubernetes_pod_name}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_stack_sys_bytes_{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "description": "**Total Used Memory**\n\n已使用内存信息\n\n* *go_memstats_sys_bytes*:服务现在系统使用的内存.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_memstats_sys_bytes_{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "description": "**Number of Live Objects**\n\n* *go_memstats_mallocs_total*:服务malloc的次数.\n* *go_memstats_frees_total*:内存释放统计.\n\n``go_memstats_mallocs_total - go_memstats_frees_total``",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}-go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "**Rate of Objects Allocated**\n\n每秒产生的堆对象数量\n\n``rate(go_memstats_mallocs_total[2m])``",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "**Rate of a Pointer Dereferences**\n\n* * go_memstats_lookups_total:被runtime监视的指针数.\n\n``rate(go_memstats_lookups_total[2m])``",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "**Goroutines**\n\n\n协程数量\n\n* *go_goroutines*:当前存在的协程数量.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_goroutines_{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "description": "**GC duration quantile**\n\n* *go_gc_duration_seconds*:垃圾收集周期的暂停持续时间.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "go_gc_duration_seconds_{{kubernetes_pod_name}}_{{quantile}}"
    }
   ]
  },
  { "title": "dataserver 指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Rate of Publish Task",
   "type": "graph",
   "description": "**Rate of Publish Task**\n\n每秒产生异步任务的速度\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dataserver_publish_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
    }
   ]
  },
  {
   "title": "Rate of Handle Task",
   "type": "graph",
   "description": "**Rate of Handle Task**\n\n每秒处理异步任务的速度",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dataserver_handle_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
    }
   ]
  },
  {
   "title": "Rate of Unprocessed Task",
   "type": "graph",
   "description": "**Num of Unprocessed Task**\n\n每秒未处理的异步任务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(sum by (queue) (rate(dataserver_publish_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m]))-sum by (queue) (rate(dataserver_handle_task{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m])),0)",
     "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
    }
   ]
  },
  {
   "title": "Current Length of Queue",
   "type": "graph",
   "description": "**Current Length of Queue**\n\n当前异步队列长度",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataserver_status_async_queue_length{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
    }
   ]
  },
  {
   "title": "Count of Publish Task Error / 10分钟",
   "type": "graph",
   "description": "**Count of Publish Task Error Per 10Minutes*\n\n异步任务产生错误统计数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dataserver_publish_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
     "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
    }
   ]
  },
  {
   "title": "Count of Handle Task Error / 10分钟",
   "type": "graph",
   "description": "**Count of Handle Task Error Per 10Minute**\n\n处理异步任务错误累计数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dataserver_handle_task_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[10m])",
     "legendFormat": "{{kubernetes_pod_name}}{{queue}}"
    }
   ]
  },
  {
   "title": "Cost Time of Api",
   "type": "graph",
   "description": "**Api Cost Time**\n\nAPI访问操作消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "dataserver_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Cost Time of Service",
   "type": "graph",
   "description": "**Cost Time of Service**\n\n服务逻辑消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "dataserver_option_service{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Cost Time of Database",
   "type": "graph",
   "description": "**Cost Time of Database**\n\n数据库访问消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "dataserver_option_database{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Cost Time of Cache",
   "type": "graph",
   "description": "**Cost Time of Cache**\n\n缓存消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "dataserver_option_cache{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Slow Option of Api",
   "type": "graph",
   "description": "**Slow of Api**\n\nAPI慢操作",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slow_dataserver_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Slow Option of Service",
   "type": "graph",
   "description": "**Slow Option of Service**\n\n服务慢操作",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slow_dataserver_option_service{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Slow Option of Database",
   "type": "graph",
   "description": "**Slow Option of Database**\n\n数据库慢操作",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slow_dataserver_option_database{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Slow Option of Cache",
   "type": "graph",
   "description": "**Slow Option of Cache**\n\n缓存慢操作",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slow_dataserver_option_cache{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "hits / 2分钟",
   "type": "graph",
   "description": "number of times free connection was found in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(go_redis_pool_stats_connections_hits{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "misses / 2分钟",
   "type": "graph",
   "description": "number of times free connection was NOT found in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(go_redis_pool_stats_connections_misses{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "timeouts",
   "type": "graph",
   "description": "number of times a wait timeout occurred",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_timeouts{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "total_conns",
   "type": "graph",
   "description": "number of total connections in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_total_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "idle_conns",
   "type": "graph",
   "description": "number of idle connections in the pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_idle_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "stale_conns",
   "type": "graph",
   "description": "number of stale connections removed from the pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_redis_pool_stats_connections_stale_conns{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Exec QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (s_command) (rate(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\"}[2m]))",
     "legendFormat": "{{s_command}}"
    }
   ]
  },
  {
   "title": "Exec Error / 5分钟",
   "type": "graph",
   "description": "每5分钟redis执行命令错误数量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error,s_command) (increase(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\",error!=\"\"}[5m]))",
     "legendFormat": "{{s_command}}-{{error}}"
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Pipeline\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Strings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Strings\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Lists",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Lists\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Keys\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "SortedSets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"SortedSets\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Hashes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Hashes\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Scripting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Scripting\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Sets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Sets\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Streams\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Geo",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\", kubernetes_pod_name=~\"$pod\", command=\"Geo\",quantile=~\"$quantile\"}",
     "legendFormat": "{{service}}-{{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "连接池最大连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataserver_connections_max_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: Max Open"
    }
   ]
  },
  {
   "title": "连接池当前连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataserver_connections_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: Open"
    }
   ]
  },
  {
   "title": "关闭连接 / 5分钟",
   "type": "graph",
   "description": "max idle: The total number of connections closed due to SetMaxIdleConns\n\nmax life time: The total number of connections closed due to SetConnMaxLifetime\n\nmax idle time: The total number of connections closed due to SetConnMaxIdleTime",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dataserver_connections_closed_max_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: max idle"
    },
    {
     "expr": "increase(dataserver_connections_closed_max_lifetime{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: max life time"
    },
    {
     "expr": "increase(dataserver_connections_closed_max_idle_time{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: max idle time"
    }
   ]
  },
  {
   "title": "使用和空闲连接数",
   "type": "graph",
   "description": "in use: The number of connections currently in use\n\nidle: The number of idle connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataserver_connections_in_use{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}: in use"
    },
    {
     "expr": "dataserver_connections_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}:  idle"
    }
   ]
  },
  {
   "title": "等待链接的待执行命令数 / 5分钟",
   "type": "graph",
   "description": "the total number of waits / 5min",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dataserver_connections_waited_for{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}} waited for"
    }
   ]
  },
  {
   "title": "获取链接阻塞时间 /秒",
   "type": "graph",
   "description": "连接池获取链接阻塞占用时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(dataserver_connections_blocked_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}: {{db_name}}"
    }
   ]
  },
  {
   "title": "TOP 10 慢查询",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, max by(query) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "错误次数/秒",
   "type": "graph",
   "description": "每秒DB错误次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_exec_timing_count{status!=\"ok\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\",query=~\"$query\"}[2m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Exec执行耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "db_exec_timing{command=\"Exec\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\",query=~\"$query\"}",
     "legendFormat": "{{query}}-{{quantile}}-{{error}}"
    }
   ]
  },
  {
   "title": "Exec QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_exec_timing_count{command=\"Exec\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",query=~\"$query\"}[2m])",
     "legendFormat": "{{query}}-{{error}}"
    }
   ]
  },
  {
   "title": "Query执行耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "db_exec_timing{command=\"Query\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\",query=~\"$query\"}",
     "legendFormat": "{{query}}-{{quantile}}-{{error}}"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_exec_timing_count{command=\"Query\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",query=~\"$query\"}[2m])",
     "legendFormat": "{{query}}-{{error}}"
    }
   ]
  },
  {
   "title": "GetHints执行耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "db_exec_timing{command=\"GetHints\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\",query=~\"$query\"}",
     "legendFormat": "{{query}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "GetHints QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_exec_timing_count{command=\"GetHints\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",query=~\"$query\"}[2m])",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Ping执行耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "db_exec_timing{command=\"Ping\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\",query=~\"$query\"}",
     "legendFormat": "{{query}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Ping QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_exec_timing_count{command=\"Ping\",job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",query=~\"$query\"}[2m])",
     "legendFormat": "{{query}}"
    }
   ]
  }
 ]
}