{
 "title": "MyProxy 1.5",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "kubernetes-pods" },
   {
    "name": "project",
    "label": "project",
    "query": "label_values(myproxy_connections_max_open,project)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(myproxy_connections_max_open{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},stage)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\"},kubernetes_pod_name)"
   },
   {
    "name": "query",
    "label": "command",
    "query": "label_values(db_exec_timing_count{job=\"$job\",project=\"$project\",env_name=\"$env\",stage=\"$stage\"}, command)"
   },
   { "name": "quantile", "label": "quantile", "query": "0.5, 0.75, 0.95, 1" }
  ]
 },
 "panels": [
  {
   "title": "MyProxy Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\",server_id=\"0\"})"
    }
   ]
  },
  {
   "title": "Mysql Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by(server_id) (myproxy_connections_max_open{job=\"$job\", project=\"$project\",env_name=\"$env\",server_id!=\"0\"}))"
    }
   ]
  },
  {
   "title": "SIID Domains",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (siid_next{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"})"
    }
   ]
  },
  {
   "title": "API QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(myproxy_option_access_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[5m]))",
     "legendFormat": "API QPS"
    }
   ]
  },
  {
   "title": "Slowest API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(myproxy_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"})"
    }
   ]
  },
  {
   "title": "DB QPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(db_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[5m]))",
     "legendFormat": "DB QPS"
    }
   ]
  },
  {
   "title": "Slowest DB",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"})"
    }
   ]
  },
  {
   "title": "DB Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(db_exec_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"})"
    }
   ]
  },
  { "title": "MyProxy  (POD:$pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "API Latency",
   "type": "graph",
   "description": "**Api Cost Time **\n\nAPI访问操作消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "myproxy_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "API QPS",
   "type": "graph",
   "description": "**Api Cost Time**\n\nAPI访问操作消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (option)(rate(myproxy_option_access_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m]))",
     "legendFormat": "{{option}}"
    }
   ]
  },
  {
   "title": "Store Latency",
   "type": "graph",
   "description": "**Cost Time of Database**\n\n数据库访问消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "myproxy_option_store{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Store QPS",
   "type": "graph",
   "description": "**Cost Time of Database**\n\n数据库访问消耗时间",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(myproxy_option_store_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m])) by (option)",
     "legendFormat": "{{option}}"
    }
   ]
  },
  {
   "title": "Slow of Api",
   "type": "graph",
   "description": "**Slow of Api**\n\nAPI慢操作",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slow_myproxy_option_access{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "Slow of Store",
   "type": "graph",
   "description": "**Slow Option of Database**\n\n数据库慢操作",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "slow_myproxy_option_store{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}_{{option}}_{{quantile}}"
    }
   ]
  },
  {
   "title": "SIID Next QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,domain) (rate(siid_next{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
    }
   ]
  },
  {
   "title": "SIID Quantum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "siid_quantum{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}",
     "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
    }
   ]
  },
  {
   "title": "SIID Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "siid_max{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}",
     "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
    }
   ]
  },
  {
   "title": "SIID Left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "siid_n_left{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}",
     "legendFormat": "{{kubernetes_pod_name}}: domain:{{domain}}"
    }
   ]
  },
  {
   "title": "DB (POD:$pod)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "pool max connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "myproxy_connections_max_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}: Max Open"
      }
     ]
    },
    {
     "title": "pool open connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "myproxy_connections_open{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}: Open"
      }
     ]
    },
    {
     "title": "pool close connections / 5 minutes",
     "type": "graph",
     "description": "max idle: The total number of connections closed due to SetMaxIdleConns\n\nmax life time: The total number of connections closed due to SetConnMaxLifetime\n\nmax idle time: The total number of connections closed due to SetConnMaxIdleTime",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(myproxy_connections_closed_max_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}: max idle"
      },
      {
       "expr": "increase(myproxy_connections_closed_max_lifetime{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}: max life time"
      },
      {
       "expr": "increase(myproxy_connections_closed_max_idle_time{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}: max idle time"
      }
     ]
    },
    {
     "title": "pool use and idle connections",
     "type": "graph",
     "description": "in use: The number of connections currently in use\n\nidle: The number of idle connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "myproxy_connections_in_use{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}: in use"
      },
      {
       "expr": "myproxy_connections_idle{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}:  idle"
      }
     ]
    },
    {
     "title": "block commands wait for connections / 5 minutes",
     "type": "graph",
     "description": "the total number of waits / 5min",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(myproxy_connections_waited_for{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}} waited for"
      }
     ]
    },
    {
     "title": "block get connections / second",
     "type": "graph",
     "description": "连接池获取链接阻塞占用时间",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(myproxy_connections_blocked_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}: db{{server_id}}"
      }
     ]
    },
    {
     "title": "TOP 10 slowest command ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(command) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}))",
       "legendFormat": "{{command}}"
      }
     ]
    },
    {
     "title": "TOP 10 Table slowest",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(table_name) (db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}))",
       "legendFormat": "{{table_name}}"
      }
     ]
    },
    {
     "title": "DB Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "db_exec_timing{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\",quantile=~\"$quantile\"}",
       "legendFormat": "{{command}}:  quantile:{{quantile}}"
      }
     ]
    },
    {
     "title": "DB Error / second",
     "type": "graph",
     "description": "每秒DB错误次数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(db_exec_error{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m])",
       "legendFormat": "{{table_name}}: {{command}}"
      }
     ]
    },
    {
     "title": "DB QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (command, table_name) (rate(db_exec_timing_count{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\"}[2m]))",
       "legendFormat": "{{table_name}}-{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "go process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "graph",
     "description": "**Memory in Off-Heap**\n\n堆外内存信息\n\n* *go_memstats_mspan_inuse_bytes*:用于测试用的结构体使用的字节数.\n* *go_memstats_mspan_sys_bytes*:系统为测试用的结构体分配的字节数.\n* *go_memstats_mcache_inuse_bytes*:mcache结构体申请的字节数(不会被视为垃圾回收).\n* *go_memstats_mcache_sys_bytes*:操作系统申请的堆空间用于mcache的字节数.\n* *go_memstats_buck_hash_sys_bytes*:用于剖析桶散列表的堆空间字节.\n* *go_memstats_gc_sys_bytes*:圾回收标记元信息使用的内存字节.\n* *go_memstats_next_gc_bytes*:垃圾回收器检视的内存大小.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mspan_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mspan_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mcache_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_mcache_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_buck_hash_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_gc_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_next_gc_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "graph",
     "description": "**Memory in Heap**\n\n堆内存信息\n* *go_memstats_heap_alloc_bytes*:服务分配的堆内存字节数.\n* *go_memstats_heap_sys_bytes*:系统分配的作为运行栈的内存.\n* *go_memstats_heap_idle_bytes*:申请但是未分配的堆内存或者回收了的堆内存（空闲）字节数.\n* *go_memstats_heap_inuse_bytes*:正在使用的堆内存字节数.\n* *go_memstats_heap_released_bytes*:返回给OS的堆内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_alloc_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_idle_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_heap_released_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "description": "**Memory in Stack**\n\n栈内存信息\n\n* *go_memstats_stack_inuse_bytes*: 正在使用的栈字节数.\n* *go_memstats_stack_sys_bytes*: 系统分配的作为运行栈的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_stack_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_stack_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "graph",
     "description": "**Total Used Memory**\n\n已使用内存信息\n\n* *go_memstats_sys_bytes*:服务现在系统使用的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_memstats_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "description": "**Number of Live Objects**\n\n* *go_memstats_mallocs_total*:服务malloc的次数.\n* *go_memstats_frees_total*:内存释放统计.\n\n``go_memstats_mallocs_total - go_memstats_frees_total``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}-go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "graph",
     "description": "**Rate of Objects Allocated**\n\n每秒产生的堆对象数量\n\n``rate(go_memstats_mallocs_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "graph",
     "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "graph",
     "description": "**Rate of a Pointer Dereferences**\n\n* * go_memstats_lookups_total:被runtime监视的指针数.\n\n``rate(go_memstats_lookups_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "**Goroutines**\n\n\n协程数量\n\n* *go_goroutines*:当前存在的协程数量.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_goroutines_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "description": "**GC duration quantile**\n\n* *go_gc_duration_seconds*:垃圾收集周期的暂停持续时间.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=\"$env\", stage=\"$stage\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "go_gc_duration_seconds_{{kubernetes_pod_name}}_{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}