{
 "title": "Sandwich框架AND基础服务指标",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(up, job)" },
   {
    "name": "project",
    "query": "label_values(up{job=\"$job\"},project)"
   },
   {
    "name": "env",
    "query": "label_values(up{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "query": "label_values(up{job=\"$job\", project=\"$project\",env_name=~\"$env\"},stage)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(up{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\"},service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(up{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\",service=~\"$service\"},kubernetes_pod_name)"
   },
   {
    "name": "uri",
    "label": "uri",
    "query": "label_values(sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\", service=~\"$service\"}, uri)"
   },
   {
    "name": "query",
    "label": "DbQuery",
    "query": "label_values(pb2db_exec_timing{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\", service=~\"$service\"}, query)"
   }
  ]
 },
 "panels": [
  { "title": "服务总览(Env:$env)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go Process ",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - sum by (service,kubernetes_pod_name,env_name)(goruntime_process_start_time_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(goruntime_process_max_fds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(goruntime_process_open_fds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(rate(goruntime_process_cpu_seconds_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m]))",
     "legendFormat": "cpu usage"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(goruntime_process_resident_memory_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})",
     "legendFormat": "mem usage"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(goruntime_process_virtual_memory_max_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(goruntime_process_virtual_memory_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
    },
    {
     "expr": "sum(rate(gonode_netdev_bytes_recv{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])*8) by (service,kubernetes_pod_name)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "sum(rate(gonode_netdev_bytes_sent{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])*8) by (service,kubernetes_pod_name)",
     "legendFormat": "上传带宽"
    },
    {
     "expr": "sum(gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}) by (service,kubernetes_pod_name)- 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "sum(gonode_sockstat_TCP_tw{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}) by (service,kubernetes_pod_name)",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "sum by (service,kubernetes_pod_name)(up{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Sandwich (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "dispatch local",
     "type": "table",
     "description": "所有服务本地响应请求指标汇总",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "label_join((sum(rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "label_join((MAX(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", quantile=\"0.5\"}) BY (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "label_join((MAX(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"}) BY (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "label_join((sum(rate(sandwich_dispatch_local_count{status=\"timeout\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "label_join((1-sum(rate(sandwich_dispatch_local_count{status=\"ok\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri) / sum(rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "dispatch remote",
     "type": "table",
     "description": "所有服务远端调用请求指标汇总",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "SUM(rate(sandwich_dispatch_remote_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"}[2m])) BY (uri)",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "MAX(sandwich_dispatch_remote_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", quantile=\"0.5\"}) BY (uri)",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "MAX(sandwich_dispatch_remote_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"}) BY (uri)",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "sum(rate(sandwich_dispatch_remote_count{status=\"timeout\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (uri)",
       "legendFormat": "{{uri}}"
      },
      {
       "expr": "1-sum(rate(sandwich_dispatch_remote_count{status=\"ok\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (uri) / sum(rate(sandwich_dispatch_remote_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "service qps",
     "type": "graph",
     "description": "选择服务的QPS",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}[2m])) by (env_name, service)",
       "legendFormat": "{{env_name}}: {{service}}"
      }
     ]
    },
    {
     "title": "QPS ",
     "type": "graph",
     "description": "每个Pod的qps",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}[2m])) by (env_name, service,kubernetes_pod_name)"
      }
     ]
    },
    {
     "title": "service latency",
     "type": "graph",
     "description": "选择服务的响应时间曲线",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}) by (env_name, service, quantile)",
       "legendFormat": "{{env_name}}: {{service}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Number of services",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service) (up{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"})",
       "legendFormat": "{{env_name}}: {{service}}"
      }
     ]
    },
    {
     "title": "service数($env)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum by (env_name,service) (up{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"})",
       "legendFormat": "{{env_name}}: {{service}}"
      }
     ]
    },
    {
     "title": "Dispatch Remote Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sandwich_dispatch_remote_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}, quantile={{quantile}}, {{uri}}"
      }
     ]
    },
    {
     "title": "Dispatch Local Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", uri=\"$uri\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}, quantile={{quantile}}, {{uri}}"
      }
     ]
    },
    {
     "title": "Ark Request QPS By Path",
     "type": "graph",
     "description": "http服务每个path的qps",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service,path,status,stage) (rate(ark_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}}: path={{path}} status={{status}}"
      }
     ]
    },
    {
     "title": "Ark Request QPS By Pod",
     "type": "graph",
     "description": "HTTP服务每个kubernetes_pod_name的QPS",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service,kubernetes_pod_name,status,stage) (rate(ark_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}}-{{stage}}-{{kubernetes_pod_name}} status={{status}}"
      }
     ]
    },
    {
     "title": "Ark Request Latency By Path",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ark_request_path_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}) by (env_name,service,stage,quantile,path)",
       "legendFormat": "{{env_name}}: {{service}}-{{path}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Ark Request Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ark_request_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}) by (env_name,service,stage,quantile)",
       "legendFormat": "{{env_name}}: {{service}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Top10 Slowest Local URI Of All pods",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(env_name,uri) (sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}))",
       "legendFormat": "{{env_name}}: {{uri}}"
      }
     ]
    },
    {
     "title": "Top10 Slowest Local URI Of ($pod)",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(uri) (sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}))",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "Top10 QPS最高的URI",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(env_name,uri)(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}[2m])))",
       "legendFormat": "{{env_name}}: {{uri}}"
      }
     ]
    },
    {
     "title": "Link Request QPS By Pod",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service,stage,status,kubernetes_pod_name) (rate(ark_plain_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}}-{{kubernetes_pod_name}} status={{status}}"
      }
     ]
    },
    {
     "title": "Link Request QPS By Path",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name, service, status, stage) (rate(link_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}} status={{status}}"
      }
     ]
    },
    {
     "title": "Ark Plain Request QPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service,stage,status,path) (rate(ark_plain_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}}: path={{path}} status={{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "hits每5分钟",
     "type": "graph",
     "description": "number of times free connection was found in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(go_redis_pool_stats_connections_hits{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "misses ",
     "type": "graph",
     "description": "number of times free connection was NOT found in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_misses{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "timeouts每5分钟",
     "type": "graph",
     "description": "number of times a wait timeout occurred",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(go_redis_pool_stats_connections_timeouts{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "total_conns",
     "type": "graph",
     "description": "number of total connections in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_total_conns{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "idle_conns",
     "type": "graph",
     "description": "number of idle connections in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_idle_conns{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "stale_conns",
     "type": "graph",
     "description": "number of stale connections removed from the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_stale_conns{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Exec QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name, s_command) (rate(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[2m]))",
       "legendFormat": "{{env_name}}: {{s_command}}"
      }
     ]
    },
    {
     "title": "Exec Error / 5分钟",
     "type": "graph",
     "description": "每5分钟redis执行命令错误数量",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name, s_command,error) (increase(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", error!=\"\"}[5m]))",
       "legendFormat": "{{env_name}}: {{s_command}}:{{error}}"
      }
     ]
    },
    {
     "title": "Pipeline",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Pipeline\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Strings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Strings\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Lists",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Lists\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Keys\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "SortedSets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"SortedSets\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "SortedSets QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"SortedSets\"}[5m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Scripting",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Scripting\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Hashes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Hashes\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Streams",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Streams\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Sets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Sets\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Geo",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Geo\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{s_command}}-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "基础指标 (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "总CPU使用时间",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service,kubernetes_pod_name)(rate(goruntime_process_cpu_seconds_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\",service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m]))",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "内存占用RSS",
     "type": "graph",
     "description": "**内存占用 RSS**\n\n* *process_resident_memory_bytes*:常驻内存大小（字节）",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "goruntime_process_resident_memory_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "每秒网络带宽使用",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps", "label": "上传（-）/下载（+）" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gonode_netdev_bytes_sent{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])*8) by (env_name,service,kubernetes_pod_name)",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_上传"
      },
      {
       "expr": "sum(rate(gonode_netdev_bytes_recv{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])*8) by (env_name,service,kubernetes_pod_name)",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_下载"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "graph",
     "description": "**Total Used Memory**\n\n已使用内存信息\n\n* *go_memstats_sys_bytes*:服务现在系统使用的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Off-Heap",
     "type": "graph",
     "description": "**Memory in Off-Heap**\n\n堆外内存信息\n\n* *mspan_inuse_bytes*:用于测试用的结构体使用的字节数.\n* *mspan_sys_bytes*:系统为测试用的结构体分配的字节数.\n* *mcache_inuse_bytes*:mcache结构体申请的字节数(不会被视为垃圾回收).\n* *mcache_sys_bytes*:操作系统申请的堆空间用于mcache的字节数.\n* *buck_hash_sys_bytes*:用于剖析桶散列表的堆空间字节.\n* *gc_sys_bytes*:圾回收标记元信息使用的内存字节.\n* *next_gc_bytes*:垃圾回收器检视的内存大小.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mspan_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mspan_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mcache_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mcache_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: buck_hash_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: gc_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: next_gc_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "网络Socket连接信息",
     "type": "graph",
     "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_tw"
      },
      {
       "expr": "gonode_sockstat_sockets_used{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Sockets_used"
      },
      {
       "expr": "gonode_sockstat_TCP_alloc{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_alloc"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_PassiveOpens{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_PassiveOpens"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_ActiveOpens{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_ActiveOpens"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_InSegs{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_InSegs"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_OutSegs{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_OutSegs"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_RetransSegs{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_RetransSegs"
      },
      {
       "expr": "rate(gonode_netstat_TcpExt_ListenDrops{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_Tcp_ListenDrops"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "description": "**Memory in Stack**\n\n栈内存信息\n\n* *stack_inuse_bytes*: 正在使用的栈字节数.\n* *stack_sys_bytes*: 系统分配的作为运行栈的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: stack_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: stack_sys_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "graph",
     "description": "**Memory in Heap**\n\n堆内存信息\n* *heap_alloc_bytes*:服务分配的堆内存字节数.\n* *heap_sys_bytes*:系统分配的作为运行栈的内存.\n* *heap_idle_bytes*:申请但是未分配的堆内存或者回收了的堆内存（空闲）字节数.\n* *heap_inuse_bytes*:正在使用的堆内存字节数.\n* *heap_released_bytes*:返回给OS的堆内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_alloc_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_sys_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_idle_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_inuse_bytes_{{kubernetes_pod_name}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_released_bytes_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "description": "**Number of Live Objects**\n\n* *go_memstats_mallocs_total*:服务malloc的次数.\n* *go_memstats_frees_total*:内存释放统计.\n\n``go_memstats_mallocs_total - go_memstats_frees_total``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}-go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "graph",
     "description": "**Rate of Objects Allocated**\n\n每秒产生的堆对象数量\n\n``rate(go_memstats_mallocs_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[5m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "graph",
     "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "graph",
     "description": "**Rate of a Pointer Dereferences**\n\n* * go_memstats_lookups_total:被runtime监视的指针数.\n\n``rate(go_memstats_lookups_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "**Goroutines**\n\n\n协程数量\n\n* *go_goroutines*:当前存在的协程数量.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: go_goroutines_{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "description": "**GC duration quantile**\n\n* *go_gc_duration_seconds*:垃圾收集周期的暂停持续时间.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}_{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PB2DB (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "max open",
     "type": "graph",
     "description": "Maximum number of open connections to the database",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_max_open{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "connections  open",
     "type": "graph",
     "description": "The number of established connections both in use and idle",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_open{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "connections closed",
     "type": "graph",
     "description": "max idle: The total number of connections closed due to SetMaxIdleConns\n\nmax life time: The total number of connections closed due to SetConnMaxLifetime\n\nmax idle time: The total number of connections closed due to SetConnMaxIdleTime",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_closed_max_idle_time{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}-{{db_name}}: max idle time"
      },
      {
       "expr": "go_sql_stats_connections_closed_max_lifetime{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}-{{db_name}}: max life time"
      },
      {
       "expr": "go_sql_stats_connections_closed_max_idle{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}-{{db_name}}: max idle"
      }
     ]
    },
    {
     "title": "blocked seconds / second",
     "type": "graph",
     "description": "The time blocked waiting for a new connection per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(go_sql_stats_connections_blocked_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "connections waited for",
     "type": "graph",
     "description": "The total number of connections waited for",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_waited_for{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "connections in use and idle",
     "type": "graph",
     "description": "in use: The number of connections currently in use\n\nidle: The number of idle connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_in_use{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}-{{db_name}}: in use"
      },
      {
       "expr": "go_sql_stats_connections_idle{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{kubernetes_pod_name}}-{{db_name}}: idle"
      }
     ]
    },
    {
     "title": "Query Exec Duration Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(pb2db_exec_timing{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\", query=~\"$query\"}) by(quantile,status,query,service)",
       "legendFormat": "{{env_name}}: {{service}} quantile={{quantile}}, status={{status}}, {{query}}"
      }
     ]
    },
    {
     "title": "Query Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,query,status,service) (rate(pb2db_exec_timing_count{status=\"ok\", job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\", query=~\"$query\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}}-{{status}}-{{query}}"
      }
     ]
    },
    {
     "title": "Top 10 Slowest Query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(env_name,query) (pb2db_exec_timing{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}))",
       "legendFormat": "{{env_name}}: {{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lighthouse (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "lighthouse id match QPS",
     "type": "graph",
     "description": "客户端传来和lighthousid和服务器存储的对比 match表示一致",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(lighthouse_id_compare_match{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])) by (channel)",
       "legendFormat": "match_{{channel}}"
      },
      {
       "expr": "sum(rate(lighthouse_id_compare_not_match{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])) by (channel)",
       "legendFormat": "NOT_match_{{channel}}"
      }
     ]
    }
   ]
  }
 ]
}