{
 "title": "Sandwich框架AND基础服务指标",
 "tags": [
  "Sandwich",
  "业务"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(up, job)" },
   {
    "name": "project",
    "query": "label_values(up{job=\"$job\"},project)"
   },
   {
    "name": "env",
    "query": "label_values(up{job=\"$job\", project=\"$project\"}, env_name)"
   },
   {
    "name": "stage",
    "query": "label_values(up{job=\"$job\", project=\"$project\",env_name=~\"$env\"},stage)"
   },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(up{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\"},service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(up{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\",service=~\"$service\"},pod)"
   },
   {
    "name": "uri",
    "label": "uri",
    "query": "label_values(sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\", service=~\"$service\"}, uri)"
   },
   {
    "name": "query",
    "label": "DbQuery",
    "query": "label_values(pb2db_exec_timing{job=\"$job\", project=\"$project\",env_name=~\"$env\",stage=\"$stage\", service=~\"$service\"}, query)"
   }
  ]
 },
 "panels": [
  {
   "title": "集群总览, 按集群名汇总 (Service:$service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dispatch Local 响应时间（逻辑处理时间）",
     "type": "graph",
     "description": "逻辑处理时间\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\",quantile=\"1\",service=~\"$service\"}) by (clusterName,service)",
       "legendFormat": " {{clusterName}}: {{service}} Max"
      },
      {
       "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\",quantile=\"0.99\",service=~\"$service\"}) by (clusterName, service)",
       "legendFormat": " {{clusterName}}: {{service}} P99"
      },
      {
       "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\",quantile=\"0.95\",service=~\"$service\"}) by (clusterName,service)",
       "legendFormat": "{{clusterName}}: {{service}} P95"
      }
     ]
    },
    {
     "title": "ARK 响应时间（包含网络IO，逻辑处理时间）",
     "type": "graph",
     "description": "包含网络IO，逻辑处理时间\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ark_request_duration_seconds{job=\"$job\", project=\"$project\",quantile=\"1\",service=~\"$service\"}) by (clusterName,service)",
       "legendFormat": "{{clusterName}}: {{service}} Max"
      },
      {
       "expr": "max(ark_request_duration_seconds{job=\"$job\", project=\"$project\",quantile=\"0.99\",service=~\"$service\"}) by (clusterName,service)",
       "legendFormat": "{{clusterName}}:  {{service}} P99"
      },
      {
       "expr": "max(ark_request_duration_seconds{job=\"$job\", project=\"$project\",quantile=\"0.95\",service=~\"$service\"}) by (clusterName,service)",
       "legendFormat": "{{clusterName}}:  {{service}} P95"
      }
     ]
    },
    {
     "title": "所有环境按照服务名汇总的QPS",
     "type": "graph",
     "description": "集群内所有环境按照服务名汇总的QPS\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\",  project=\"$project\", service=~\"$service\"}[2m])) by (clusterName,service)",
       "legendFormat": "{{clusterName}}: {{service}}"
      }
     ]
    },
    {
     "title": "所有环境按照服务名汇总逻辑处理异常",
     "type": "graph",
     "description": "集群内所有环境按照服务名汇总的逻辑处理异常\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sandwich_dispatch_local_count{job=\"$job\",  project=\"$project\", service=~\"$service\", status!=\"\", status!=\"ok\"}[2m])) by (clusterName, service,status)",
       "legendFormat": "{{clusterName}}: {{service}}: status:{{status}}"
      }
     ]
    },
    {
     "title": "所有环境按照服务名汇总的Socket连接数",
     "type": "graph",
     "description": "集群内所有环境按照服务名汇总的Socket连接数\n\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (clusterName,service) (gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", service=~\"$service\"})",
       "legendFormat": "{{clusterName}} {{service}}"
      }
     ]
    },
    {
     "title": "所有环境按照服务名汇总ARK异常",
     "type": "graph",
     "description": "集群内所有环境按照服务名汇总的ARK异常\n\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ark_requests_total{job=\"$job\",  project=\"$project\", service=~\"$service\", status!=\"\", status!=\"ok\"}[2m])) by (clusterName,service,status)",
       "legendFormat": "{{clusterName}}: {{service}}: status:{{status}}"
      }
     ]
    },
    {
     "title": "所有环境按照服务名汇总QPS环比昨日百分比",
     "type": "graph",
     "description": "(QPS - 昨日QPS)*100 / 昨日QPS\n\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", service=~\"$service\"}[2m])) by ( clusterName,service)-sum(rate(sandwich_dispatch_local_count{job=\"$job\",  project=\"$project\", service=~\"$service\"}[2m] offset 24h )) by (clusterName,service))*100/sum(rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", service=~\"$service\"}[2m] offset 24h )) by (clusterName,service)",
       "legendFormat": "{{clusterName}}: {{service}}"
      }
     ]
    },
    {
     "title": "所有环境按照服务名汇总Socket连接数环比昨日百分比",
     "type": "graph",
     "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\n\n所有环境内的服务按照物理集群和服务名汇总统计，可以通过筛选服务只统计制定服务，其他筛选不起作用",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum by (clusterName,service) (gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", service=~\"$service\"})-sum by (clusterName,service) (gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\",  service=~\"$service\"} offset 24h))*100 /sum by (clusterName,service) (gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", service=~\"$service\"} offset 24h)",
       "legendFormat": "{{clusterName}}-{{stage}}:{{service}} _CurrEstab"
      }
     ]
    }
   ]
  },
  {
   "title": "选择环境内的服务总览(环境:$env)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go服务概况 环境:$env",
     "type": "table",
     "description": "筛选env显示当前go服务的状态，这个表格只是显示当前的最新值，有的单元格可能为空，想看趋势可以看下面的曲线",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "time() - sum by (service,pod,env_name)(goruntime_process_start_time_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
      },
      {
       "expr": "sum by (service,pod)(goruntime_process_open_fds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
      },
      {
       "expr": "sum by (service,pod)(rate(goruntime_process_cpu_seconds_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m]))",
       "legendFormat": "cpu usage"
      },
      {
       "expr": "sum by (service,pod)(goruntime_process_resident_memory_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})",
       "legendFormat": "mem usage"
      },
      {
       "expr": "sum by (service,pod)(goruntime_process_virtual_memory_max_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
      },
      {
       "expr": "sum by (service,pod)(goruntime_process_virtual_memory_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})"
      },
      {
       "expr": "sum(rate(gonode_netdev_bytes_recv{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])*8) by (service,pod)",
       "legendFormat": "下载带宽"
      },
      {
       "expr": "sum(rate(gonode_netdev_bytes_sent{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])*8) by (service,pod)",
       "legendFormat": "上传带宽"
      },
      {
       "expr": "sum(gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}) by (service,pod)- 0",
       "legendFormat": "连接数"
      },
      {
       "expr": "sum(gonode_sockstat_TCP_tw{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}) by (service,pod)",
       "legendFormat": "TIME_WAIT"
      },
      {
       "expr": "sum by (service,pod)(up{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"})",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "按照服务名汇总QPS",
     "type": "graph",
     "description": "上方筛选环境按照服务名汇总的QPS\n\n这里会跟筛选框选择的env和service筛选数据，然后按照env和service汇总计算",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\",  project=\"$project\",env_name=~\"$env\", service=~\"$service\"}[2m])) by (env_name,service)",
       "legendFormat": "{{env_name}}: {{service}}"
      }
     ]
    },
    {
     "title": "按照服务名汇总Socket连接数",
     "type": "graph",
     "description": "上方筛选环境按照服务名汇总的Socket连接数\n\n这里会跟筛选框选择的env和service筛选数据，然后按照env和service汇总计算",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service) (gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\",env_name=~\"$env\", service=~\"$service\"})",
       "legendFormat": "{{env_name}} {{service}}"
      }
     ]
    },
    {
     "title": "网络带宽",
     "type": "graph",
     "description": "上传下载带宽，注意单位是b\n\n这里会跟筛选框选择的env和service筛选数据，然后按照env和service汇总计算",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gonode_netdev_bytes_sent{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])*8) by (env_name, service)",
       "legendFormat": "{{env_name}}-{{service}}_上传"
      },
      {
       "expr": "sum(rate(gonode_netdev_bytes_recv{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])*8) by (env_name,service)",
       "legendFormat": "{{env_name}}-{{service}}_下载"
      }
     ]
    },
    {
     "title": "ARK Request Latency (MAX)",
     "type": "graph",
     "description": "ARK服务响应时间的最大值，包含逻辑处理时间和IO时间\n\n\n这里会跟筛选框选择的env和service筛选数据，然后按照env和service汇总计算",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ark_request_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}) by (service)",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "选择环境内 选择的Sandwich服务指标 (环境:$env, 服务:$service, Stage:$stage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Dispatch Local （逻辑处理汇总）",
   "type": "table",
   "description": "所有服务逻辑处理指标汇总，所选时间段内的Last状态。所以有的表格可能是空，想看趋势可以看下面的曲线\n\n这里会根据筛选的 env, service, stage 过滤数据",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_join((sum(rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "label_join((MAX(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", quantile=\"0.5\"}) BY (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "label_join((MAX(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"}) BY (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "label_join((sum(rate(sandwich_dispatch_local_count{status=\"timeout\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "label_join((1-sum(rate(sandwich_dispatch_local_count{status=\"ok\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri) / sum(rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (env_name,uri)), \"uri\",\": \",\"env_name\",\"uri\")",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Dispatch Remote (远端调用模式)",
   "type": "table",
   "description": "所有服务远端调用请求指标汇总，只有开启远程调用的服务才会有这个指标\n\n这里会根据筛选的 env, service, stage 过滤数据",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "SUM(rate(sandwich_dispatch_remote_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"}[2m])) BY (uri)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "MAX(sandwich_dispatch_remote_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", quantile=\"0.5\"}) BY (uri)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "MAX(sandwich_dispatch_remote_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\"}) BY (uri)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum(rate(sandwich_dispatch_remote_count{status=\"timeout\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (uri)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "1-sum(rate(sandwich_dispatch_remote_count{status=\"ok\", job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (uri) / sum(rate(sandwich_dispatch_remote_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\"}[2m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "服务数量 (环境:$env)",
   "type": "bargauge",
   "description": "显示当前探测到的服务数量\n\n这里会根据筛选的 env, stage 过滤数据",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (env_name,service,stage) (up{job=\"$job\", env_name=~\"$env\", project=\"$project\",stage=\"$stage\"})",
     "legendFormat": "{{env_name}}: {{service}}"
    }
   ]
  },
  {
   "title": "服务数量 (环境:$env)",
   "type": "graph",
   "description": "反应历史服务数量的曲线\n\n这里会根据筛选的 env, service, stage 过滤数据",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name,service,stage) (up{job=\"$job\", env_name=~\"$env\", project=\"$project\",stage=\"$stage\"})",
     "legendFormat": "{{env_name}}: {{service}}"
    }
   ]
  },
  {
   "title": "Dispatch Local QPS（逻辑处理）",
   "type": "graph",
   "description": "选择环境内服务的QPS\n\n这里会根据筛选的 env, service 过滤数据",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", service=~\"$service\"}[2m])) by (env_name, service)",
     "legendFormat": "{{env_name}}: {{service}}"
    }
   ]
  },
  {
   "title": "ARK QPS",
   "type": "graph",
   "description": "选择环境内服务的ARK QPS，这里表示收到的http请求的QPS，与逻辑处理可能有差异，因为有些请求读超时，或者解析包失败 不会进入逻辑处理\n\n这里会根据筛选的 env, service 过滤数据",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ark_request_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", service=~\"$service\"}[2m])) by (env_name, service)",
     "legendFormat": "{{env_name}}: {{service}}"
    }
   ]
  },
  {
   "title": "服务逻辑处理异常",
   "type": "graph",
   "description": "集群所选环境按照服务名汇总的逻辑处理异常",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sandwich_dispatch_local_count{job=\"$job\",  project=\"$project\", service=~\"$service\",env_name=~\"$env\", status!=\"\", status!=\"ok\"}[2m])) by (env_name,service,status)",
     "legendFormat": "{{env_name}}-{{service}}: status:{{status}}"
    }
   ]
  },
  {
   "title": "ARK 处理异常",
   "type": "graph",
   "description": "集群所选环境按照服务名汇总的 ARK 处理异常",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ark_requests_total{job=\"$job\",  project=\"$project\", service=~\"$service\",env_name=~\"$env\", status!=\"\", status!=\"ok\"}[2m])) by (env_name,service,status)",
     "legendFormat": "{{env_name}}-{{service}}: status:{{status}}"
    }
   ]
  },
  {
   "title": "Dispatch Local 响应时间（逻辑处理时间）",
   "type": "graph",
   "description": "逻辑处理响应时间",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\",quantile=\"1\"}) by (env_name, service)",
     "legendFormat": "{{env_name}}: {{service}} MAX"
    },
    {
     "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\",quantile=\"0.99\"}) by (env_name, service)",
     "legendFormat": "{{env_name}}: {{service}} 99分位"
    },
    {
     "expr": "max(sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\",quantile=\"0.95\"}) by (env_name, service)",
     "legendFormat": "{{env_name}}: {{service}} 95分位"
    }
   ]
  },
  {
   "title": "ARK 响应时间（包含网络IO，逻辑处理时间）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(ark_request_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",quantile=\"1\"}) by (env_name,service)",
     "legendFormat": "{{env_name}}: {{service}} Max"
    },
    {
     "expr": "avg(ark_request_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",quantile=\"0.99\"}) by (env_name,service)",
     "legendFormat": "{{env_name}}: {{service}} 99分位"
    },
    {
     "expr": "avg(ark_request_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",quantile=\"0.95\"}) by (env_name,service)",
     "legendFormat": "{{env_name}}: {{service}} 95分位"
    }
   ]
  },
  {
   "title": "URI Latency (URI: $uri)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (env_name,service,quantile, uri) (sandwich_dispatch_local_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", uri=\"$uri\", stage=\"$stage\", service=~\"$service\"})",
     "legendFormat": "{{env_name}}-{{service}}: {{uri}}: quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "ARK 读取请求Body时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(ark_read_body_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",quantile=\"1\"}) by (env_name,service)",
     "legendFormat": "{{env_name}}: {{service}} Max"
    },
    {
     "expr": "avg(ark_read_body_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",quantile=\"0.99\"}) by (env_name,service)",
     "legendFormat": "{{env_name}}: {{service}} 99分位"
    },
    {
     "expr": "avg(ark_read_body_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",quantile=\"0.95\"}) by (env_name,service)",
     "legendFormat": "{{env_name}}: {{service}} 95分位"
    }
   ]
  },
  {
   "title": "URI QPS (URI: $uri)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (env_name,service, uri) (rate(sandwich_dispatch_local_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", uri=\"$uri\", stage=\"$stage\", service=~\"$service\"}[2m]))",
     "legendFormat": "{{env_name}}-{{service}}: {{uri}}"
    }
   ]
  },
  {
   "title": "每个Path的ARK Latency ",
   "type": "graph",
   "description": "ark按照path纬度统计耗时情况",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(ark_request_path_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}) by (env_name,service,quantile,path)",
     "legendFormat": "{{env_name}}: {{service}}-{{path}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "每个Pod的 Dispatch Local QPS (Pod:$pod)",
   "type": "graph",
   "description": "每个Pod的qps",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sandwich_dispatch_local_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}[2m])) by (env_name,service,pod,status)",
     "legendFormat": "{{env_name}}: {{pod}} status: {{status}}"
    }
   ]
  },
  {
   "title": "每个Path的读取Body耗时",
   "type": "graph",
   "description": "ark按照path纬度统计读取Body耗时情况",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(ark_read_body_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}) by (env_name,service,quantile,path)",
     "legendFormat": "{{env_name}}: {{service}}-{{path}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "Dispatch Remote 响应时间(远端调用模式)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (env_name,quantile, uri) (sandwich_dispatch_remote_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"})",
     "legendFormat": "{{env_name}}:  quantile={{quantile}}, {{uri}}"
    }
   ]
  },
  {
   "title": "每个Path的ARK QPS (环境:$env, 服务:$service, Stage:$stage)",
   "type": "graph",
   "description": "http服务每个path的qps",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name,service,path,status) (rate(ark_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m]))",
     "legendFormat": "{{env_name}}: {{service}}: path={{path}} status={{status}}"
    }
   ]
  },
  {
   "title": "Common Http Request QPS",
   "type": "graph",
   "description": "http 通用服务qps (非sandwich框架)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name,service,path,http_status) (rate(http_server_request_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", service=~\"$service\"}[2m]))",
     "legendFormat": "{{env_name}}-{{service}}:{{path}} status: {{http_status}}"
    }
   ]
  },
  {
   "title": "每个Pod的ARK QPS (Pod:$pod)",
   "type": "graph",
   "description": "HTTP服务每个pod的QPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name,service,pod,status) (rate(ark_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{env_name}}: {{pod}} status={{status}}"
    }
   ]
  },
  {
   "title": "Common Http Request QPS",
   "type": "graph",
   "description": "http 通用服务qps (非sandwich框架)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (rate(http_server_request_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", service=~\"$service\"}[2m]))",
     "legendFormat": "{{env_name}}-{{service}}: {{http_status}}"
    }
   ]
  },
  {
   "title": "Common Http Request Latency P95",
   "type": "graph",
   "description": "Http通用服务耗时（非sandwich协议）",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum by(env_name,service,path,le)(rate(http_server_latency_bucket{job=\"$job\", project=\"$project\", env_name=~\"$env\", service=~\"$service\"}[2m])))",
     "legendFormat": "{{env_name}}-{{service}}: {{path}} P95"
    }
   ]
  },
  {
   "title": "Top10 Slowest Local URI  (环境:$env, 服务:$service, Stage:$stage)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, max by(env_name,service,uri) (sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}))",
     "legendFormat": "{{env_name}}-{{service}}: {{uri}}"
    }
   ]
  },
  {
   "title": "Top10 Slowest Local URI  (环境:$env, 服务:$service, Stage:$stage, Pod:$pod) ",
   "type": "graph",
   "description": "选择环境，服务，stage，pod 内的按照uri获取TOP 10",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, max by(uri) (sandwich_dispatch_local_duration_seconds{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Top10 QPS最高的URI (环境:$env, 服务:$service, Stage:$stage) ",
   "type": "graph",
   "description": "选择的环境，服务，Stage内的所有URI的TOP 10",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, max by(env_name,uri)(sum by(env_name,uri)(rate(sandwich_dispatch_local_duration_seconds_count{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}[2m]))))"
    }
   ]
  },
  {
   "title": "ARK Plain QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name,service,stage,status,path) (rate(ark_plain_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m]))",
     "legendFormat": "{{env_name}}: {{service}}: path={{path}} status={{status}}"
    }
   ]
  },
  {
   "title": "每个Pod的 ARK Plain QPS(Pod: $pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name,service,stage,status,pod) (rate(ark_plain_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{env_name}}: {{service}}-{{pod}} status={{status}}"
    }
   ]
  },
  {
   "title": "Link Request QPS By Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (env_name, service, status, stage) (rate(link_requests_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m]))",
     "legendFormat": "{{env_name}}: {{service}} status={{status}}"
    }
   ]
  },
  {
   "title": "Redis (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache hits 每5分钟",
     "type": "graph",
     "description": "RESP3协议下的本地cache",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(redis_cache_hits{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "cache miss 每5分钟",
     "type": "graph",
     "description": "RESP3协议下的本地cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(redis_cache_miss{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "pool hits每5分钟",
     "type": "graph",
     "description": "number of times free connection was found in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(go_redis_pool_stats_connections_hits{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "pool misses ",
     "type": "graph",
     "description": "number of times free connection was NOT found in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_misses{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "pool timeouts每5分钟",
     "type": "graph",
     "description": "number of times a wait timeout occurred",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(go_redis_pool_stats_connections_timeouts{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[5m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "pool total conns",
     "type": "graph",
     "description": "number of total connections in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_total_conns{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "pool idle conns",
     "type": "graph",
     "description": "number of idle connections in the pool",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_idle_conns{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "pool stale conns",
     "type": "graph",
     "description": "number of stale connections removed from the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_redis_pool_stats_connections_stale_conns{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "Exec QPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name, s_command) (rate(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[2m]))",
       "legendFormat": "{{env_name}}: {{s_command}}"
      }
     ]
    },
    {
     "title": "Exec Error / 5分钟",
     "type": "graph",
     "description": "每5分钟redis执行命令错误数量",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name, s_command,error) (increase(redis_exec_timing_count{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", error!=\"\"}[5m]))",
       "legendFormat": "{{env_name}}: {{s_command}}:{{error}}"
      }
     ]
    },
    {
     "title": "Pipeline命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Pipeline\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "String命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Strings|String\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "List命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Lists|List\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Hash命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Hashes|Hash\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "SortedSet命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"SortedSets|SortedSet\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Set命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Sets|Set\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Scripting命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Scripting\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Bitmap命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Bitmap\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Stream命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Streams|Stream\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Keys命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Keys|Key\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Server命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=\"Server\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Geospatial命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Geo|Geospatial\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Generic命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Generic\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Connection命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"Connection\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "HyperLog命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"HyperLog\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    },
    {
     "title": "Geospatial命令集执行耗时",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_exec_timing{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", command=~\"PubSub\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{s_command}}-{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "基础指标 (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 },
   "collapsed": true,
   "panels": [
    {
     "title": "总CPU使用时间",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,service,pod)(rate(goruntime_process_cpu_seconds_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\",service=~\"$service\",pod=~\"$pod\"}[2m]))",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "内存占用RSS",
     "type": "graph",
     "description": "**内存占用 RSS**\n\n* *process_resident_memory_bytes*:常驻内存大小（字节）",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "goruntime_process_resident_memory_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "每秒网络带宽使用",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps", "label": "上传（-）/下载（+）" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gonode_netdev_bytes_sent{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])*8) by (env_name,service,pod)",
       "legendFormat": "{{env_name}}: {{pod}}_上传"
      },
      {
       "expr": "sum(rate(gonode_netdev_bytes_recv{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])*8) by (env_name,service,pod)",
       "legendFormat": "{{env_name}}: {{pod}}_下载"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "graph",
     "description": "**Total Used Memory**\n\n已使用内存信息\n\n* *go_memstats_sys_bytes*:服务现在系统使用的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "Memory in Off-Heap",
     "type": "graph",
     "description": "**Memory in Off-Heap**\n\n堆外内存信息\n\n* *mspan_inuse_bytes*:用于测试用的结构体使用的字节数.\n* *mspan_sys_bytes*:系统为测试用的结构体分配的字节数.\n* *mcache_inuse_bytes*:mcache结构体申请的字节数(不会被视为垃圾回收).\n* *mcache_sys_bytes*:操作系统申请的堆空间用于mcache的字节数.\n* *buck_hash_sys_bytes*:用于剖析桶散列表的堆空间字节.\n* *gc_sys_bytes*:圾回收标记元信息使用的内存字节.\n* *next_gc_bytes*:垃圾回收器检视的内存大小.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mspan_inuse_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mspan_sys_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mcache_inuse_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: mcache_sys_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: buck_hash_sys_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: gc_sys_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\", pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: next_gc_bytes_{{pod}}"
      }
     ]
    },
    {
     "title": "网络Socket连接信息",
     "type": "graph",
     "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "gonode_netstat_Tcp_CurrEstab{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}_CurrEstab"
      },
      {
       "expr": "node_sockstat_TCP_tw{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_tw"
      },
      {
       "expr": "gonode_sockstat_sockets_used{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}_Sockets_used"
      },
      {
       "expr": "gonode_sockstat_TCP_alloc{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_alloc"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_PassiveOpens{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_PassiveOpens"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_ActiveOpens{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_ActiveOpens"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_InSegs{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_InSegs"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_OutSegs{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_OutSegs"
      },
      {
       "expr": "rate(gonode_netstat_Tcp_RetransSegs{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_RetransSegs"
      },
      {
       "expr": "rate(gonode_netstat_TcpExt_ListenDrops{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}_Tcp_ListenDrops"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "description": "**Memory in Stack**\n\n栈内存信息\n\n* *stack_inuse_bytes*: 正在使用的栈字节数.\n* *stack_sys_bytes*: 系统分配的作为运行栈的内存.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: stack_inuse_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: stack_sys_bytes_{{pod}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "graph",
     "description": "**Memory in Heap**\n\n堆内存信息\n* *heap_alloc_bytes*:服务分配的堆内存字节数.\n* *heap_sys_bytes*:系统分配的作为运行栈的内存.\n* *heap_idle_bytes*:申请但是未分配的堆内存或者回收了的堆内存（空闲）字节数.\n* *heap_inuse_bytes*:正在使用的堆内存字节数.\n* *heap_released_bytes*:返回给OS的堆内存.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_alloc_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_sys_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_idle_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_inuse_bytes_{{pod}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: heap_released_bytes_{{pod}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "graph",
     "description": "**Number of Live Objects**\n\n* *go_memstats_mallocs_total*:服务malloc的次数.\n* *go_memstats_frees_total*:内存释放统计.\n\n``go_memstats_mallocs_total - go_memstats_frees_total``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}-go_memstats_frees_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "graph",
     "description": "**Rate of Objects Allocated**\n\n每秒产生的堆对象数量\n\n``rate(go_memstats_mallocs_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[5m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "graph",
     "description": "**Rates of Allocation**\n\n内存分配速度\n\n* *go_memstats_alloc_bytes_total*:Go内存统计分配字节总数.\n\n``rate(go_memstats_alloc_bytes_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "graph",
     "description": "**Rate of a Pointer Dereferences**\n\n* * go_memstats_lookups_total:被runtime监视的指针数.\n\n``rate(go_memstats_lookups_total[2m])``",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "description": "**Goroutines**\n\n\n协程数量\n\n* *go_goroutines*:当前存在的协程数量.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: go_goroutines_{{pod}}"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "graph",
     "description": "**GC duration quantile**\n\n* *go_gc_duration_seconds*:垃圾收集周期的暂停持续时间.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}_{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PB2DB (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "累计错误",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env,stage,service,tableName,query) (pb2db_exec_error{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"})",
       "legendFormat": "{{env}}: {{service}}: {{tableName}}: {{query}}"
      }
     ]
    },
    {
     "title": "connections  open",
     "type": "graph",
     "description": "The number of established connections both in use and idle",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_open{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "max open",
     "type": "graph",
     "description": "Maximum number of open connections to the database",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_max_open{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "blocked seconds / second",
     "type": "graph",
     "description": "The time blocked waiting for a new connection per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(go_sql_stats_connections_blocked_seconds{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}[2m])",
       "legendFormat": "{{env_name}}: {{pod}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "connections closed",
     "type": "graph",
     "description": "max idle: The total number of connections closed due to SetMaxIdleConns\n\nmax life time: The total number of connections closed due to SetConnMaxLifetime\n\nmax idle time: The total number of connections closed due to SetConnMaxIdleTime",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_closed_max_idle_time{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}-{{db_name}}: max idle time"
      },
      {
       "expr": "go_sql_stats_connections_closed_max_lifetime{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}-{{db_name}}: max life time"
      },
      {
       "expr": "go_sql_stats_connections_closed_max_idle{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}-{{db_name}}: max idle"
      }
     ]
    },
    {
     "title": "connections in use and idle",
     "type": "graph",
     "description": "in use: The number of connections currently in use\n\nidle: The number of idle connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_in_use{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}-{{db_name}}: in use"
      },
      {
       "expr": "go_sql_stats_connections_idle{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}-{{db_name}}: idle"
      }
     ]
    },
    {
     "title": "connections waited for",
     "type": "graph",
     "description": "The total number of connections waited for",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_sql_stats_connections_waited_for{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\",pod=~\"$pod\"}",
       "legendFormat": "{{env_name}}: {{pod}}: {{db_name}}"
      }
     ]
    },
    {
     "title": "Query Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (env_name,query,status,service) (rate(pb2db_exec_timing_count{status=\"ok\", job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\", query=~\"$query\"}[5m]))",
       "legendFormat": "{{env_name}}: {{service}}-{{status}}-{{query}}"
      }
     ]
    },
    {
     "title": "Query Exec Duration Quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(pb2db_exec_timing{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\", query=~\"$query\"}) by(quantile,status,query,service)",
       "legendFormat": "{{env_name}}: {{service}} quantile={{quantile}}, status={{status}}, {{query}}"
      }
     ]
    },
    {
     "title": "Top 10 Slowest Query",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, max by(env_name,query) (pb2db_exec_timing{job=\"$job\", env_name=~\"$env\", project=\"$project\", stage=\"$stage\", service=~\"$service\"}))",
       "legendFormat": "{{env_name}}: {{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Lighthouse (Env:$env, Service: $service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "lighthouse id match QPS",
     "type": "graph",
     "description": "客户端传来和lighthousid和服务器存储的对比 match表示一致",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(lighthouse_id_compare_match{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])) by (channel)",
       "legendFormat": "match_{{channel}}"
      },
      {
       "expr": "sum(rate(lighthouse_id_compare_not_match{job=\"$job\", project=\"$project\", env_name=~\"$env\", stage=\"$stage\", service=~\"$service\"}[2m])) by (channel)",
       "legendFormat": "NOT_match_{{channel}}"
      }
     ]
    }
   ]
  }
 ]
}